// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu_DFx0SYnpVkMLfbi8CaJ8a1bOXbArpA',
    appId: '1:773476503273:web:17b6c7f60a1c8a9a3d2a78',
    messagingSenderId: '773476503273',
    projectId: 'porto3-57801',
    authDomain: 'porto3-57801.firebaseapp.com',
    storageBucket: 'porto3-57801.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtduJ0-cvn5NQazjRMP7PACNoGIcsOUdU',
    appId: '1:773476503273:android:77ff330d1d10028a3d2a78',
    messagingSenderId: '773476503273',
    projectId: 'porto3-57801',
    storageBucket: 'porto3-57801.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-VkSK9HIHlGTJx3FTvLKP3cy1JzIAais',
    appId: '1:773476503273:ios:d23a377652cab04d3d2a78',
    messagingSenderId: '773476503273',
    projectId: 'porto3-57801',
    storageBucket: 'porto3-57801.appspot.com',
    iosBundleId: 'com.example.letterboxdPorto3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-VkSK9HIHlGTJx3FTvLKP3cy1JzIAais',
    appId: '1:773476503273:ios:d23a377652cab04d3d2a78',
    messagingSenderId: '773476503273',
    projectId: 'porto3-57801',
    storageBucket: 'porto3-57801.appspot.com',
    iosBundleId: 'com.example.letterboxdPorto3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu_DFx0SYnpVkMLfbi8CaJ8a1bOXbArpA',
    appId: '1:773476503273:web:f336ed8353f021d73d2a78',
    messagingSenderId: '773476503273',
    projectId: 'porto3-57801',
    authDomain: 'porto3-57801.firebaseapp.com',
    storageBucket: 'porto3-57801.appspot.com',
  );
}
